# Formative Assignment (amended)

**Deadline: Please see Canvas**

There are 5 exercises in these assignment. Each completed exercise is awarded 7 points for a total of 35 points. In order to pass the final assigment you will need to reach at least 40 points out of 100.

Please send your solutions to the Weekly Classes Office (weeklyclasses@conted.ox.ac.uk) with a signed DoA (Declaration of Authorship) form. Please send the notebook with your name appended to the file name.

In [1]:
## Let's import the libraries we are going to use later on
import numpy as np
import pandas as pd

# Let's set the precision for NumPy and Pandas
np.set_printoptions(precision=3)
pd.options.display.float_format = '{:,.2f}'.format

## Exercises on Data Structures

### 1. Compute statistics on a Python list [7 points]
Given the following list
```
l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]
```
Compute the mean, the median and the standard deviation of the values in the list, using only built-in functionalities of python (no imported libraries, no NumPy or Pandas)

In [2]:
from math import ceil
from math import sqrt

l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]


# Write your solution here
print("Count of Values ",len(l))
sum = 0
mean = 0
median = 0
middle = 0
for i in l:
    #print(i)
    sum = sum + i
print("Sum",sum)
mean = sum / len(l)
print("Mean",mean)
l.sort()
middle = ceil(len(l)/2)
print("Middle",middle)
median = l[middle]
print("Median",median)

std_dev = 0
std_dev_sum = 0
for s in l:
    std_dev_sum = std_dev_sum + ((s-mean)**2)  
#    print("Std Dev",s,((s-mean)**2))  
#print("std dev sum",std_dev_sum)
std_dev = sqrt((1/len(l)*(std_dev_sum)))    
print("Standard Deviation (Population)",std_dev)

Count of Values  13
Sum 1296
Mean 99.6923076923077
Middle 7
Median 17
Standard Deviation (Population) 260.6044407837537


### 2A. Create a dictionary from a list of tuples (records) [3 points]

Given the following list of tuples, each one holding a record
```
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]
```
Convert them into a list of dictionaries, using the first tuple as keys for all the dictionaries and all the other tuples as values, one per dictionary. 
Expected result:

```
books = [{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]
```

In [4]:
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]
keys = records[0]
#print("",keys) 

records.pop(0)
#print("",keys) 

books = []
for i in records:
    my_books = {}
    k = 0
    for x in i:
        my_books[keys[k]] = x
        k = k+1
    books.append(my_books)
books
#print(books)

[{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]

### 2B. Dictionary manipulation [4 points]
Write a function that takes the dictionary like `books` and return the author whose book has the highest page count. 

Apply the function to `books` to verify that it works correctly

In [1]:
## Write your solution here
 
def max_page_count(book_list):

    l_page_count = -1
    l_author = ""
    for x in book_list:
        if x.get("page_count") > l_page_count:
            l_page_count = x.get("page_count")
            l_author = x.get("author")
    return l_author
 
author = ""
author = max_page_count(books)
author

NameError: name 'books' is not defined

## Exercises on Numpy

For these exercises we will work on the IRIS dataset, a very popular multivariate dataset for data anaylisis, first introduced by Ronald Fisher in 1936.

See more about the IRIS dataset heare: https://archive.ics.uci.edu/ml/datasets/Iris

The data source is the file `iris.data` retrieved from the Web. It contains the data for this example in comma separated values (CSV) format. The number of columns is 5 and the number of rows is 150. The data set is composed of 50 samples from each of three species of Iris Flower: Iris Setosa, Iris Virginica and Iris Versicolor. Four features were measured from each sample: the length and the width of the sepals and petals, in centimetres. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species one from each other.

The variables are:

    sepal_length: Sepal length, in centimeters.
    sepal_width: Sepal width, in centimeters.
    petal_length: Petal length, in centimeters.
    petal_width: Petal width, in centimeters.

The three categories of Irises are: 'Iris Setosa', 'Iris Versicolor', and 'Iris Virginica'. 

Let's first import the `iris` dataset as a 1-dimensional array of tuples.

In [6]:
import numpy as np
# Input:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(
    url, delimiter=',', 
    names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species'],
    dtype=[np.float64, np.float64, np.float64, np.float64, 'U15']
)
iris

array([(5.1, 3.5, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, 'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, 'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, 'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, 'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, 'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, 'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, 'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, 'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, 'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, 'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, 'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, 'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, 'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, 'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, 'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, 'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, 'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, 'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, 'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, 'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, 'Iris-setosa'),
       (4.6, 3.6, 1. , 0.2, 'Iri

### 3A. How to convert a 1d array of tuples to a 2d numpy array [4 points]

Exercise: convert the `iris` 1D array to a numeric-only 2D array `iris_data` by omitting the species text field. Create a `iris_label` 1D array containing only the species text field. Keep the same indexing/order as in the original array.

In [7]:
## Write your solution here
iris_data = np.array([list(row)[1:4] for row in iris])
iris_labels = np.array([list(row)[4] for row in iris])
print(iris_data[:150])
print(iris_labels[:150])



[[3.5 1.4 0.2]
 [3.  1.4 0.2]
 [3.2 1.3 0.2]
 [3.1 1.5 0.2]
 [3.6 1.4 0.2]
 [3.9 1.7 0.4]
 [3.4 1.4 0.3]
 [3.4 1.5 0.2]
 [2.9 1.4 0.2]
 [3.1 1.5 0.1]
 [3.7 1.5 0.2]
 [3.4 1.6 0.2]
 [3.  1.4 0.1]
 [3.  1.1 0.1]
 [4.  1.2 0.2]
 [4.4 1.5 0.4]
 [3.9 1.3 0.4]
 [3.5 1.4 0.3]
 [3.8 1.7 0.3]
 [3.8 1.5 0.3]
 [3.4 1.7 0.2]
 [3.7 1.5 0.4]
 [3.6 1.  0.2]
 [3.3 1.7 0.5]
 [3.4 1.9 0.2]
 [3.  1.6 0.2]
 [3.4 1.6 0.4]
 [3.5 1.5 0.2]
 [3.4 1.4 0.2]
 [3.2 1.6 0.2]
 [3.1 1.6 0.2]
 [3.4 1.5 0.4]
 [4.1 1.5 0.1]
 [4.2 1.4 0.2]
 [3.1 1.5 0.1]
 [3.2 1.2 0.2]
 [3.5 1.3 0.2]
 [3.1 1.5 0.1]
 [3.  1.3 0.2]
 [3.4 1.5 0.2]
 [3.5 1.3 0.3]
 [2.3 1.3 0.3]
 [3.2 1.3 0.2]
 [3.5 1.6 0.6]
 [3.8 1.9 0.4]
 [3.  1.4 0.3]
 [3.8 1.6 0.2]
 [3.2 1.4 0.2]
 [3.7 1.5 0.2]
 [3.3 1.4 0.2]
 [3.2 4.7 1.4]
 [3.2 4.5 1.5]
 [3.1 4.9 1.5]
 [2.3 4.  1.3]
 [2.8 4.6 1.5]
 [2.8 4.5 1.3]
 [3.3 4.7 1.6]
 [2.4 3.3 1. ]
 [2.9 4.6 1.3]
 [2.7 3.9 1.4]
 [2.  3.5 1. ]
 [3.  4.2 1.5]
 [2.2 4.  1. ]
 [2.9 4.7 1.4]
 [2.9 3.6 1.3]
 [3.1 4.4 1.4]
 [3.  4.5 

### 3B. Split the IRIS dataset by Label [3 points]


Split the dataset in `iris_data` according to the labels `iris_labels`. 

In [8]:
# Write your solution here

# Write your solution here

# Solution 1
#iris_by_label = {}
#for label in set(iris_labels):
#    iris_by_label[label] = iris_data[iris_labels == label]
#print(iris_by_label)

# Solution 2: dict comprehension
iris_by_label = {
    label: iris_data[iris_labels == label] for label in set(iris_labels)
}
print(iris_by_label)

{'Iris-versicolor': array([[3.2, 4.7, 1.4],
       [3.2, 4.5, 1.5],
       [3.1, 4.9, 1.5],
       [2.3, 4. , 1.3],
       [2.8, 4.6, 1.5],
       [2.8, 4.5, 1.3],
       [3.3, 4.7, 1.6],
       [2.4, 3.3, 1. ],
       [2.9, 4.6, 1.3],
       [2.7, 3.9, 1.4],
       [2. , 3.5, 1. ],
       [3. , 4.2, 1.5],
       [2.2, 4. , 1. ],
       [2.9, 4.7, 1.4],
       [2.9, 3.6, 1.3],
       [3.1, 4.4, 1.4],
       [3. , 4.5, 1.5],
       [2.7, 4.1, 1. ],
       [2.2, 4.5, 1.5],
       [2.5, 3.9, 1.1],
       [3.2, 4.8, 1.8],
       [2.8, 4. , 1.3],
       [2.5, 4.9, 1.5],
       [2.8, 4.7, 1.2],
       [2.9, 4.3, 1.3],
       [3. , 4.4, 1.4],
       [2.8, 4.8, 1.4],
       [3. , 5. , 1.7],
       [2.9, 4.5, 1.5],
       [2.6, 3.5, 1. ],
       [2.4, 3.8, 1.1],
       [2.4, 3.7, 1. ],
       [2.7, 3.9, 1.2],
       [2.7, 5.1, 1.6],
       [3. , 4.5, 1.5],
       [3.4, 4.5, 1.6],
       [3.1, 4.7, 1.5],
       [2.3, 4.4, 1.3],
       [3. , 4.1, 1.3],
       [2.5, 4. , 1.3],
       [2.6, 4.4, 1.

### 4. Compute statistics with Numpy [7 points]

1) For each flower species compute the key statistics for `sepal width`:
- mean
- median
- standard deviation

Answer the following questions:

    a) Which is the flower type with the largest mean value for `sepal_width`?
    b) Which is the flower type with the smallest median value for `sepal_width`?
    
2) Compute the correlation matrix between `sepal_width` and `petal_length` for the three scpecies. Which is the species that shows the highest correlation among the two parameters?

In [ ]:
### Compute mean, median, and standard deviation for `sepal width` here:

statistics = {}
for f_type, dataset in iris_by_label.items():
    statistics[f_type] = {
        'mean': np.mean(dataset, axis=0),
        'median': np.median(dataset, axis=0),
        'std': np.std(dataset, axis=0)
}
statistics


{'Iris-versicolor': {'mean': array([2.77 , 4.26 , 1.326]),
  'median': array([2.8 , 4.35, 1.3 ]),
  'std': array([0.31064449, 0.46518813, 0.19576517])},
 'Iris-virginica': {'mean': array([2.974, 5.552, 2.026]),
  'median': array([3.  , 5.55, 2.  ]),
  'std': array([0.31925538, 0.54634787, 0.27188968])},
 'Iris-setosa': {'mean': array([3.418, 1.464, 0.244]),
  'median': array([3.4, 1.5, 0.2]),
  'std': array([0.37719491, 0.17176728, 0.10613199])}}

In [17]:
### Compute the correlation coefficients here
cor_mat = {
    label: dict(cov=np.corrcoef(dataset.T)) for label, dataset in iris_by_label.items()
}
print("correlation coefficients",cor_mat)


# Compute the covariance matrix here

cov_mat = {
    label: dict(cov=np.cov(dataset.T)) for label, dataset in iris_by_label.items()
}
print(cov_mat)

### DDOF is by default == 0 in np.var while it is == 1 for np.cov

cov_mat = {
    label: dict(cov=np.cov(dataset.T, ddof=0)) for label, dataset in iris_by_label.items()
}
cov_mat



correlation coefficients {'Iris-versicolor': {'cov': array([[1.        , 0.56052209, 0.66399872],
       [0.56052209, 1.        , 0.78666809],
       [0.66399872, 0.78666809, 1.        ]])}, 'Iris-virginica': {'cov': array([[1.        , 0.40104458, 0.53772803],
       [0.40104458, 1.        , 0.32210822],
       [0.53772803, 0.32210822, 1.        ]])}, 'Iris-setosa': {'cov': array([[1.        , 0.17669463, 0.27997289],
       [0.17669463, 1.        , 0.30630821],
       [0.27997289, 0.30630821, 1.        ]])}}
{'Iris-versicolor': {'cov': array([[0.09846939, 0.08265306, 0.04120408],
       [0.08265306, 0.22081633, 0.07310204],
       [0.04120408, 0.07310204, 0.03910612]])}, 'Iris-virginica': {'cov': array([[0.10400408, 0.07137959, 0.04762857],
       [0.07137959, 0.30458776, 0.04882449],
       [0.04762857, 0.04882449, 0.07543265]])}, 'Iris-setosa': {'cov': array([[0.14517959, 0.01168163, 0.01143673],
       [0.01168163, 0.03010612, 0.00569796],
       [0.01143673, 0.00569796, 0.0114938

{'Iris-versicolor': {'cov': array([[0.0965  , 0.081   , 0.04038 ],
         [0.081   , 0.2164  , 0.07164 ],
         [0.04038 , 0.07164 , 0.038324]])},
 'Iris-virginica': {'cov': array([[0.101924, 0.069952, 0.046676],
         [0.069952, 0.298496, 0.047848],
         [0.046676, 0.047848, 0.073924]])},
 'Iris-setosa': {'cov': array([[0.142276, 0.011448, 0.011208],
         [0.011448, 0.029504, 0.005584],
         [0.011208, 0.005584, 0.011264]])}}

### 5. How to create a new column from existing columns of a numpy array [7 points]

Create a new column for the flower volume V in `iris`, where volume is computing according to this formula (the assumption here is that the shape of the iris flower is approximately conical):

$$ Volume = \frac{\pi \times Sepal Length^2 \times Petal Length}{3}$$

In [84]:
import math 
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
#iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

iris_data = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3], skip_header=True)
iris_labels = np.genfromtxt(url, delimiter=',', dtype='|S15', usecols=[4], skip_header=True)


#iris_calc =  (math.pi *((iris_data[:, 0])** 2) * iris_data[:, 2]) / 3
iris_calc =  (math.pi * ((iris_data[:, 0]** 2) * iris_data[:, 2])) /3

# Introduce new dimension to match hw_data 2-dimensions
iris_calc = iris_calc[:,np.newaxis]

iris_data = np.hstack((iris_data, iris_calc))
iris_data

array([[4.90000000e+00, 3.00000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.52004985e+01],
       [4.70000000e+00, 3.20000000e+00, 1.30000000e+00, 2.00000000e-01,
        3.00723721e+01],
       [4.60000000e+00, 3.10000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.32380503e+01],
       [5.00000000e+00, 3.60000000e+00, 1.40000000e+00, 2.00000000e-01,
        3.66519143e+01],
       [5.40000000e+00, 3.90000000e+00, 1.70000000e+00, 4.00000000e-01,
        5.19116770e+01],
       [4.60000000e+00, 3.40000000e+00, 1.40000000e+00, 3.00000000e-01,
        3.10221803e+01],
       [5.00000000e+00, 3.40000000e+00, 1.50000000e+00, 2.00000000e-01,
        3.92699082e+01],
       [4.40000000e+00, 2.90000000e+00, 1.40000000e+00, 2.00000000e-01,
        2.83832424e+01],
       [4.90000000e+00, 3.10000000e+00, 1.50000000e+00, 1.00000000e-01,
        3.77148198e+01],
       [5.40000000e+00, 3.70000000e+00, 1.50000000e+00, 2.00000000e-01,
        4.58044209e+01],
       [4.80000000e+00, 3.4000